### ISSUE TITLE
html encode error

### ISSUE THREAD

**Issue by jangarita** [as3/as3-utils#18]
I found an error in htmlEncode.as when i try to encode a string with several special characters.

I also found 2 solutions...
1. Switch line 8 and 9, the first one should be
2. Using this method
   return new XML(new XMLNode(XMLNodeType.TEXT_NODE, s)).toXMLString();
   to decode use this...
   return new XMLDocument(s).firstChild.nodeValue;

**Comment by chrisdeely** [comment]
Can you make the changes and issue a pull request?

**Comment by mimshwright** [comment]
fixed.
